export default function TermsOfService() {
  return (
    <main style={{ maxWidth: 800, margin: '0 auto', padding: '60px 24px', fontFamily: 'sans-serif', lineHeight: 1.7 }}>
      <h1>Terms of Service</h1>
      <p><strong>Last updated:</strong> June 11, 2026</p>
      <p>By using the Blitz STRIKER WhatsApp assistant, you agree to these terms.</p>
      <h2>Use of Service</h2>
      <p>The Blitz STRIKER assistant is provided for informational purposes and to facilitate contact with Blitz Digital. You agree not to use the service for any unlawful purpose.</p>
      <h2>Limitations</h2>
      <p>Blitz Digital reserves the right to discontinue or modify the service at any time without notice.</p>
      <h2>Intellectual Property</h2>
      <p>All content and responses generated by the assistant are property of Blitz Digital.</p>
      <h2>Contact</h2>
      <p>For questions about these terms, contact us at blitz.elsalvador@gmail.com or WhatsApp +503 7910 2453.</p>
    </main>
  )
}
